### ISSUE TITLE
plugin says it's compatible with adapt v2.4 - but it isn't

### ISSUE THREAD

**Issue by moloko** [aut0poietic/adapt-lottie#1]
according to this line in bower.json:
https://github.com/aut0poietic/adapt-lottie/blob/82579423ffc91ab8fc1b2fe7399159732340f326/bower.json#L4
But this line of code:
https://github.com/aut0poietic/adapt-lottie/blob/82579423ffc91ab8fc1b2fe7399159732340f326/js/adapt-lottie.js#L66
means it isn't - because this functionality was only added to ComponentView in Adapt v3.3

Also worth mentioning that the `getInviewElementSelector` functionality is something that's quite specific to the adapt-contrib-text component - it's needed for that component because title/instruction/body are all optional, whereas this component will always have something to display (the animation).

**Comment by aut0poietic** [comment]
Thanks @moloko. I'll try to play with this in a day or so -- I've got some other minor improvements I made as a part of another project that I haven't had time to incorporate as well ( setting intrinsicWidth of the SVG for IE 11 ). 

In your opinion, Is it worth checking for 4+ in-view methods ( like `setupInviewCompletion` ), then if those are absent setting up a 2.4-style inview check or just implementing the standard inview (like that of the 2.4-compatible Graphic?

**Comment by moloko** [comment]
@aut0poietic if you want to keep supporting v2.4 I'd just do a standard inview graphic component style `inview` check. Personally, I'd do that, release it then move on to supporting more recent versions in future releases (i.e. go back to using `setupInviewCompletion`). The main benefit to using `setupInviewCompletion` is to avoid having to have all the `inview` code in your component - so I don't really see any advantage in trying to support both styles.
